### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by vr4dude316** [Shinoa-Fores/joulecoin#3]
make fails with...

cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
Makefile:5501: recipe for target 'qt/qt_joulecoin_qt-bitcoin.o' failed
make[2]: *** [qt/qt_joulecoin_qt-bitcoin.o] Error 1
make[2]: Leaving directory '/home/pool/joulecoin/src'
Makefile:6253: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/pool/joulecoin/src'
Makefile:573: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
pool@ubuntu17:~/joulecoin$ unrecognized command line option ‘-Wno-self-assign’

**Comment by Shinoa-Fores** [comment]
See https://github.com/Shinoa-Fores/joulecoin/commit/ef4aec11469b57b252781e1905f5e093be349311
